[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Identity uchun redirect (kerak bo'lsa)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
