backend:
  name: git-gateway
  branch: main
 
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

#commit_messages

# When using local backend, you need to run `npx decap-server` to start the local server
# local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
site_url: https://novotoys-catalogs-app.vercel.app

# Publish mode - editorial workflow enables drafts
# publish_mode: editorial_workflow


collections:
  - name: "categories"
    label: "Kategoriyalar"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nomi", name: "title", widget: "string" }
      - { label: "Rasm", name: "image", widget: "image" }
    
  - name: "products"
    label: "Mahsulotlar"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nomi", name: "name", widget: "string" }
      - { label: "Asosiy rasm", name: "mainImage", widget: "image" }
      - { label: "Qo'shimcha rasmlar", name: "gallery", widget: "list", field: { label: "Rasm", name: "image", widget: "image" } }
      - { label: "Narxi", name: "price", widget: "string" }
      - { label: "Tavsif", name: "description", widget: "markdown" }
      - { 
          label: "Kategoriya", 
          name: "category", 
          widget: "relation", 
          collection: "categories", 
          search_fields: ["title"], 
          value_field: "title", 
          display_fields: ["title"] 
        }

# sssss
